<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cz.ecis</groupId>
		<artifactId>ecis-spring-project</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>ecis-backend</artifactId>

	<name>ECIS Backend</name>
	<description>ECIS backend application</description>

	<dependencies>

		<dependency>
			<groupId>cz.ecis</groupId>
			<artifactId>ecis-core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-quartz</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>

		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-liquibase</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>dev.samstevens.totp</groupId>
			<artifactId>totp</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers-postgresql</artifactId>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
							<goal>build-info</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>camp</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/camp.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>sec</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/sec.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>child</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/child.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>parent</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/parent.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>lookup</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/lookup.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								LovDto=cz.ecis.core.model.LovDto,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
					<execution>
						<id>env</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/src/main/resources/openapi/env.yaml</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>cz.ecis.api</apiPackage>
							<modelPackage>cz.ecis.model.dto</modelPackage>
							<apiNameSuffix>ApiInterface</apiNameSuffix>
							<importMappings>
								EnvTypeEnum=cz.ecis.core.environment.EnvTypeEnum,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</importMappings>
							<typeMappings>
								EnvTypeEnum=cz.ecis.core.environment.EnvTypeEnum,
								ErrorDto=cz.ecis.core.model.ErrorDto
							</typeMappings>
							<configOptions>
								<useSpringBoot4>true</useSpringBoot4>
								<interfaceOnly>true</interfaceOnly>
								<useBeanValidation>true</useBeanValidation>
								<delegatePattern>false</delegatePattern>
								<useJakartaEe>true</useJakartaEe>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>

	</build>

</project>