CREATE DATABASE ecis;

CREATE ROLE ecis WITH LOGIN PASSWORD 'ecis';
ALTER DATABASE ecis OWNER TO ecis;

CREATE ROLE ecis_apl WITH LOGIN PASSWORD 'ecis_apl';
CREATE ROLE ecis_ext_apl WITH LOGIN PASSWORD 'ecis_ext_apl';